---
- name: Deploy Flask BMI Calculator on Fedora
  hosts: servers
  remote_user: root

  vars:
    app_name: bmi_calculator
    app_dir: /home/student/bmi_calculator
    venv_dir: /home/student/bmi_calculator/venv
    flask_app_file: app.py
    flask_app_port: 8000

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Create virtual environment
      command: python3 -m venv "{{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Install Flask in virtual environment
      command: "{{ venv_dir }}/bin/pip install flask"

    - name: Deploy Flask application files
      copy:
        src: "{{ item.src }}"
        dest: "{{ app_dir }}/{{ item.dest }}"
      with_items:
        - { src: 'app.py', dest: 'app.py' }
        - { src: 'templates/index.html', dest: 'templates/index.html' }
        - { src: 'templates/result.html', dest: 'templates/result.html' }

    - name: Run Flask application
      shell:
        nohup python {{ app_dir }}/app.py &
